version: '3.2'

services:
  turtlesim:
    build: .
    environment: 
      - DISPLAY=${DISPLAY}
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: bash -c "ros2 run turtlesim turtlesim_node "
  bridge_container:
    build: .
    stdin_open: true
    tty: true
    command: bin/bash
    depends_on: [turtlesim]
  talker:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "ros2 run talker"
  listener:
    build: .
    stdin_open: 
    build: .
    stdin_open: true
    tty: true
    command: bash -c "ros2 run listener"
    depends_on: [talker]
      
